# 启动端口号
server:
  post: 8000

# MySQL数据源配置
mysql:
  username: work
  password: czc092709
  url: tcp(120.48.17.120:3306)/mall?charset=utf8&parseTime=True&loc=Local

# 图片路径配置
upload:
  savePath: /Users/work/resource/images/
  accessUrl: http://localhost:8000/image/

# JWT配置
jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h

# 定时任务
cron:
  enable: true

# 微信小程序相关配置
code2Session:
  appId: wxfca03cb8f6378647
  appSecret: b149cfd4f2609eec20eed5bd917fc7ea

# 问题反馈配置
feedback:
  qqSmtp: smtp.qq.com
  qqEmail: 1933757688@qq.com
  qqEmailSecret: jjstmwtidhwhxhzc